/* Database schema to keep the structure of entire database. */

CREATE DATABASE vet-clinic;

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(155) NOT NULL,
    date_of_birth date NOT NULL,
    escape_attempts INT NOT NULL,
    neutered BOOLEAN,
    weight_kg DECIMAL(3.2),
);

ALTER TABLE animals ADD COLUMN species VARCHAR(55);